version: '3'

services:
  mysql-gui:
    container_name: "mysql-gui"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_URL=mysql://root:root@host.docker.internal:3306